#ifndef INVENTORY_MODE_LOCAL_H
#define INVENTORY_MODE_LOCAL_H

enum inventory_mode_index {
    MAIN_MENU_TITLE,
    SHOW_GEAR,
    SHOW_EQUIPPED_GEAR,
    SHOW_POTIONS,
    INVENTORY_FULL_MSG,
    INVENTORY_EMPTY_MSG,
    INVENTORY_MENU_TITLE,
    INVENTORY_MENU_HEADER,
    INVENTORY_DROP_GEAR_MSG,
    INVENTORY_GEAR_FORMAT,
    INVENTORY_GEAR_FORMAT_EMPTY,

    EQUIPMENT_MENU_TITLE,
    EQUIPMENT_MENU_HEADER,

    POTION_FORMAT,
    POTION_MENU_TITLE,
    POTION_MENU_HEADER,
    POTION_FULL_MSG,
    POTION_EMPTY_MSG,
    POTION_DROP_POTION_MSG,

    LOOT_GEAR_MENU_HEADER,
    LOOT_POTION_MENU_HEADER,
    FINISH_LOOTING_MSG,

    PRESS_C_RETURN,
    MAX_INVENTORY_STRINGS
};

extern char** inventory_mode_strings;

void update_inventory_local(void);

#endif//INVENTORY_MODE_LOCAL_H
