var annotated_dup =
[
    [ "ability_init_t", "structability__init__t.html", null ],
    [ "ability_t", "structability__t.html", null ],
    [ "ability_table_t", "structability__table__t.html", null ],
    [ "character_t", "structcharacter__t.html", null ],
    [ "damage_resistance_t", "structdamage__resistance__t.html", null ],
    [ "db_connection_t", "structdb__connection__t.html", null ],
    [ "defenses_t", "structdefenses__t.html", null ],
    [ "gear_init_t", "structgear__init__t.html", null ],
    [ "gear_t", "structgear__t.html", null ],
    [ "gear_table_t", "structgear__table__t.html", null ],
    [ "input_event_t", "structinput__event__t.html", null ],
    [ "input_timing_t", "structinput__timing__t.html", null ],
    [ "loaded_visual_s", "structloaded__visual__s.html", null ],
    [ "observer_node", "structobserver__node.html", null ],
    [ "potion_init_t", "structpotion__init__t.html", null ],
    [ "potion_t", "structpotion__t.html", null ],
    [ "potion_table_t", "structpotion__table__t.html", null ],
    [ "resources_t", "structresources__t.html", null ],
    [ "ring_buffer_t", "structring__buffer__t.html", null ],
    [ "save_info_container_t", "structsave__info__container__t.html", null ],
    [ "save_info_t", "structsave__info__t.html", null ],
    [ "stats_t", "structstats__t.html", null ],
    [ "string_max_t", "structstring__max__t.html", null ],
    [ "thread_func_wrapper_t", "structthread__func__wrapper__t.html", null ],
    [ "vector2d_t", "structvector2d__t.html", null ]
];