name: auto-clang-format.yml
on:
  push:
    branches:
      - develop  # Trigger on push to develop branch
  pull_request:
    branches:
      - develop  # Trigger on pull request to develop branch

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Clang-Format v19
        run: | 
          sudo apt install -y clang-format-19

      - name: Format Code
        run: |
          find src/ test/ -type f \( -name '*.c' -o -name '*.h' \) | xargs clang-format-14 -i

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --staged --quiet || git commit -m "Auto-format code"
          git push
