name: Compile test

on:
#  pull_request:
#    branches:
#      - develop
  workflow_run:
    workflows: [ "Auto clang-format" ]
    types:
      - completed
#  push:
#    branches:
#      - develop


jobs:
  build:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }} # skip if the previous workflow failed
#    if: github.event.workflow_run.conclusion == 'success' || github.actor == 'github-actions'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Multi-OS build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies for Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build gcc g++ 

      # Install dependencies for macOS
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install meson ninja
          
      # Configure Meson
      - name: Configure Meson
        run: meson setup builddir

      # Compile project using Ninja
      - name: Compile project
        run: ninja -C builddir

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
