name: Compile in develop

on:
  push:
    branches:
      - develop  # Trigger in develop
  pull_request:
    branches:
      - develop
  

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Multi-OS build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies for Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build gcc g++ clang-tidy

      # Install dependencies for macOS
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install meson ninja clang-tidy
          
      # Configure Meson
      - name: Configure Meson
        run: meson setup builddir

      # Compile project using Ninja
      - name: Compile project
        run: ninja -C builddir

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
