name: Build & Release Executable

on:
  push:
    branches:
      - main  # Trigger only on main branch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Multi-OS build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies for Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build gcc g++ 

      # Install dependencies for macOS
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install meson ninja
          
      # Configure Meson
      - name: Configure Meson
        run: meson setup builddir

      # Compile project using Ninja
      - name: Compile project
        run: ninja -C builddir

      # Upload the executables as artifacts
      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ runner.os }}
          path: builddir/my_executable${{ '' }}

  release:
    needs: build
    runs-on: ubuntu-latest  # Push the release from Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Latest Version Tag
        id: get_version
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            latest_tag="v0.1.0"  # Default version if no tags exist
          fi
          echo "LATEST_VERSION=$latest_tag" >> $GITHUB_ENV

      # Bump the version (Patch)
      - name: Bump Version (Patch)
        id: bump_version
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ env.LATEST_VERSION }}
          level: patch

      # Create a new git tag for the release
      - name: Create New Git Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ steps.bump_version.outputs.new_version }}
          git push origin ${{ steps.bump_version.outputs.new_version }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          name: Release ${{ steps.bump_version.outputs.new_version }}
          body: "Release: Built from the latest commit."
          draft: false
          prerelease: false
          files: |
            executable-ubuntu-latest/my_executable
            executable-macos-latest/my_executable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
