name: Build & Release Executable

on:
  push:
    branches:
      - main  # Trigger only on main branch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest,windows-latest]  # Multi-OS build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies for Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build gcc python3-pip libnotcurses-dev
          pip3 install gcovr

      # Install dependencies for macOS
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
            brew install meson ninja notcurses
          
      - name: Build on Windows (MSYS2 MinGW64)
        runs-on: windows-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup MSYS2
            uses: msys2/setup-msys2@v2
            with:
              msystem: MINGW64
              update: true
              install: >-
                mingw-w64-x86_64-toolchain
                mingw-w64-x86_64-meson
                mingw-w64-x86_64-ninja
                mingw-w64-x86_64-notcurses

          - name: Build with Meson and Ninja
            shell: msys2 {0}
            run: |
              meson setup builddir --buildtype=release
              ninja -C builddir
      # Configure Meson
      - name: Configure Meson
        run: meson setup builddir

      # Compile project using Ninja
      - name: Compile project
        run: ninja -C builddir

      # Upload the executables as artifacts
      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeonCrawl-executable-${{ runner.os }}
          path: builddir/DungeonCrawl

  release:
    needs: build
    runs-on: ubuntu-latest  # Push the release from Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto Tag Release
        id: auto_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch  # Can be 'patch', 'minor', or 'major'
          WITH_V: true  # Adds 'v' prefix (e.g., v1.0.1)

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts  # Store all artifacts in the 'artifacts/' folder

      - name: Rename Artifacts for Clarity #There will be a conflict due to files having the same name otherwhise
        run: |
          mv artifacts/dungeonCrawl-executable-Linux/DungeonCrawl artifacts/dungeonCrawl-executable-Linux/DungeonCrawl-Linux
          mv artifacts/dungeonCrawl-executable-macOS/DungeonCrawl artifacts/dungeonCrawl-executable-macOS/DungeonCrawl-macOS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.auto_tag.outputs.new_tag }}
          name: Release ${{ steps.auto_tag.outputs.new_tag }}
          body: "Release: Built from the latest commit."
          draft: false
          prerelease: false
          files: |
            artifacts/dungeonCrawl-executable-Linux/DungeonCrawl-Linux
            artifacts/dungeonCrawl-executable-macOS/DungeonCrawl-macOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
