name: Build & Release Executable

on:
  push:
    branches:
      - main  # Trigger only on main branch
      
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build gcc python3-pip libnotcurses-dev zip
          pip3 install gcovr

      - name: Build
        run: |
          meson setup builddir --buildtype=release
          ninja -C builddir

      - name: Create package
        run: |
          mkdir -p release-linux
          cp builddir/DungeonCrawl release-linux/
          cp -r database/ release-linux/ || true
          cp -r resources/ release-linux/ || true
          cd release-linux
          zip -r ../dungeonCrawl-Linux.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeonCrawl-executable-${{ runner.os }}
          path: builddir/DungeonCrawl-Linux.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install meson ninja notcurses

      - name: Build
        run: |
          meson setup builddir --buildtype=release
          ninja -C builddir

      - name: Create package
        run: |
          mkdir -p release-macos
          cp builddir/DungeonCrawl release-macos/
          cp -r database/ release-macos/ || true
          cp -r resources/ release-macos/ || true
          cd release-macos
          zip -r ../dungeonCrawl-macOS.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeonCrawl-executable-${{ runner.os }}
          path: builddir/DungeonCrawl-macOS.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-notcurses
            zip

      - name: Compile
        shell: msys2 {0}
        run: |
          meson setup builddir --buildtype=release
          ninja -C builddir

      - name: Create package
        shell: msys2 {0}
        run: |
          mkdir -p release-windows
          cp builddir/DungeonCrawl.exe release-windows/
          cp -r database/ release-windows/ || true
          cp -r resources/ release-windows/ || true
          cd release-windows
          zip -r ../dungeonCrawl-Windows.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeonCrawl-executable-${{ runner.os }}
          path: builddir/DungeonCrawl-Windows.zip

  release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Auto Tag Release
        id: auto_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Rename Artifacts for Clarity #There will be a conflict due to files having the same name otherwhise
        run: |
          mv artifacts/dungeonCrawl-executable-Linux/ artifacts/dungeonCrawl-executable-Linux/DungeonCrawl-Linux.zip
          mv artifacts/dungeonCrawl-executable-macOS/ artifacts/dungeonCrawl-executable-macOS/DungeonCrawl-macOS.zip
          mv artifacts/dungeonCrawl-executable-macOS/ artifacts/dungeonCrawl-executable-macOS/DungeonCrawl-Windows.zip


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.auto_tag.outputs.new_tag }}
          name: Release ${{ steps.auto_tag.outputs.new_tag }}
          body: "Release: Built from the latest commit. Each package contains the executable, database, and resource files."
          draft: false
          prerelease: false
          files: |
	          artifacts/dungeonCrawl-executable-Linux/DungeonCrawl-Linux.zip
            artifacts/dungeonCrawl-executable-macOS/DungeonCrawl-macOS.zip
            artifacts/dungeonCrawl-executable-Windows/DungeonCrawl-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
