name: Build & Release Executable

on:
  push:
    branches:
      - main  # Trigger only on main branch
      
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build gcc python3-pip libnotcurses-dev zip
          pip3 install gcovr

      - name: Build
        run: |
          meson setup builddir --buildtype=release
          ninja -C builddir

        # Statements that contain "|| true" are optional 
      - name: Create package
        run: |
          mkdir -p release-linux
          cp builddir/DungeonCrawl release-linux/
          cp Manual.pdf release-linux/ || true
          cp -r resources/ release-linux/ || true
          cd release-linux
          zip -r ../dungeonCrawl-Linux.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeonCrawl-executable-Linux
          path: dungeonCrawl-Linux.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install meson ninja notcurses

      - name: Build
        run: |
          meson setup builddir --buildtype=release
          ninja -C builddir

        # Statements that contain "|| true" are optional 
      - name: Create package
        run: |
          mkdir -p release-macos
          mkdir -p release-macos/resources
          cp builddir/DungeonCrawl release-macos/
          cp -r resources/ release-macos/resources || true
          cp Manual.pdf release-macos/ || true
          cd release-macos
          zip -r ../dungeonCrawl-macOS.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeonCrawl-executable-macOS
          path: dungeonCrawl-macOS.zip

  release:
    needs: [build-linux, build-macos]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Auto Tag Release
        id: auto_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
  
      - name: Debug List artifact contents
        run: ls -R artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.auto_tag.outputs.new_tag }}
          name: Release ${{ steps.auto_tag.outputs.new_tag }}
          body: "Release: Built from the latest commit. Each package contains the executable, database, and resource files."
          draft: false
          prerelease: false
          files: |
            artifacts/dungeonCrawl-executable-Linux/dungeonCrawl-Linux.zip
            artifacts/dungeonCrawl-executable-macOS/dungeonCrawl-macOS.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
